CREATE TABLE TradingSignals (
    dateAndTime SMALLDATETIME
    MSFT_MACD DECIMAL
    MSFT_GRADIENT DECIMAL
    MFST_PRICE DECIMAL
    MFST_TRADE CHAR
    MFST_PROFIT DECIMAL
    MSFT_RETURN DECIMAL
    --
    KO_MACD DECIMAL
    KO_GRADIENT DECIMAL
    KO_PRICE DECIMAL
    KO_TRADE CHAR
    KO_PROFIT DECIMAL
    KO_RETURN DECIMAL
    --
    XOM_MACD DECIMAL
    XOM_GRADIENT DECIMAL
    XOM_PRICE DECIMAL
    XOM_TRADE CHAR
    XOM_PROFIT DECIMAL
    XOM_RETURN DECIMAL
    --
    INTC_MACD DECIMAL
    INTC_GRADIENT DECIMAL
    INTC_PRICE DECIMAL
    INTC_TRADE CHAR
    INTC_PROFIT DECIMAL
    INTC_RETURN DECIMAL
    --
    JNJ_MACD DECIMAL
    JNJ_GRADIENT DECIMAL
    JNJ_PRICE DECIMAL
    JNJ_TRADE CHAR
    JNJ_PROFIT DECIMAL
    JNJ_RETURN DECIMAL
    --
    PG_MACD DECIMAL
    PG_GRADIENT DECIMAL
    PG_PRICE DECIMAL
    PG_TRADE CHAR
    PG_PROFIT DECIMAL
    PG_RETURN DECIMAL
    --
    PFE_MACD DECIMAL
    PFE_GRADIENT DECIMAL
    PFE_PRICE DECIMAL
    PFE_TRADE CHAR
    PFE_PROFIT DECIMAL
    PFE_RETURN DECIMAL
    --
    DIS_MACD DECIMAL
    DIS_GRADIENT DECIMAL
    DIS_PRICE DECIMAL
    DIS_TRADE CHAR
    DIS_PROFIT DECIMAL
    DIS_RETURN DECIMAL
    --
    AXP_MACD DECIMAL
    AXP_GRADIENT DECIMAL
    AXP_PRICE DECIMAL
    AXP_TRADE CHAR
    AXP_PROFIT DECIMAL
    AXP_RETURN DECIMAL
    --
    GS_MACD DECIMAL
    GS_GRADIENT DECIMAL
    GS_PRICE DECIMAL
    GS_TRADE CHAR
    GS_PROFIT DECIMAL
    GS_RETURN DECIMAL
    --
    V_MACD DECIMAL
    V_GRADIENT DECIMAL
    V_PRICE DECIMAL
    V_TRADE CHAR
    V_PROFIT DECIMAL
    V_RETURN DECIMAL
    --
    VZ_MACD DECIMAL
    VZ_GRADIENT DECIMAL
    VZ_PRICE DECIMAL
    VZ_TRADE CHAR
    VZ_PROFIT DECIMAL
    VZ_RETURN DECIMAL
    --
    WMT_MACD DECIMAL
    WMT_GRADIENT DECIMAL
    WMT_PRICE DECIMAL
    WMT_TRADE CHAR
    WMT_PROFIT DECIMAL
    WMT_RETURN DECIMAL
    --
    MCD_MACD DECIMAL
    MCD_GRADIENT DECIMAL
    MCD_PRICE DECIMAL
    MCD_TRADE CHAR
    MCD_PROFIT DECIMAL
    MCD_RETURN DECIMAL
    --
    BA_MACD DECIMAL
    BA_GRADIENT DECIMAL
    BA_PRICE DECIMAL
    BA_TRADE CHAR
    MCD_PROFIT DECIMAL
    MCD_RETURN DECIMAL
    --
    CSCO_MACD DECIMAL
    CSCO_GRADIENT DECIMAL
    CSCO_PRICE DECIMAL
    CSCO_TRADE CHAR
    CSCO_PROFIT DECIMAL
    CSCO_RETURN DECIMAL
    --
    NKE_MACD DECIMAL
    NKE_GRADIENT DECIMAL
    NKE_PRICE DECIMAL
    NKE_TRADE CHAR
    NKE_PROFIT DECIMAL
    NKE_RETURN DECIMAL
    --
    JPM_MACD DECIMAL
    JPM_GRADIENT DECIMAL
    JPM_PRICE DECIMAL
    JPM_TRADE CHAR
    JPM_PROFIT DECIMAL
    JPM_RETURN DECIMAL
    --
    MRK_MACD DECIMAL
    MRK_GRADIENT DECIMAL
    MRK_PRICE DECIMAL
    MRK_TRADE CHAR
    MRK_PROFIT DECIMAL
    MRK_RETURN DECIMAL
    --
    CVX_MACD DECIMAL
    CVX_GRADIENT DECIMAL
    CVX_PRICE DECIMAL
    CVX_TRADE CHAR
    CVX_PROFIT DECIMAL
    CVX_RETURN DECIMAL
);


